import { selector } from "recoil"

import {
  CHARACTER_CREATION_PRIORITIES_A,
  CHARACTER_CREATION_PRIORITIES_B,
  CHARACTER_CREATION_PRIORITIES_C,
  CHARACTER_CREATION_PRIORITIES_D,
  CHARACTER_CREATION_PRIORITIES_E,
} from "../index"

export const WITH_PRIORITIES = selector({
  key: 'WITH_PRIORITIES',
  get: ({ get }) => {
    return {
      A: get(CHARACTER_CREATION_PRIORITIES_A),
      B: get(CHARACTER_CREATION_PRIORITIES_B),
      C: get(CHARACTER_CREATION_PRIORITIES_C),
      D: get(CHARACTER_CREATION_PRIORITIES_D),
      E: get(CHARACTER_CREATION_PRIORITIES_E),
    }
  }
})