import { selector } from "recoil"

import {
  CHARACTER_CREATION_HISTORY_BIRTH,
  CHARACTER_CREATION_HISTORY_NOW,
  CHARACTER_CREATION_HISTORY_RAISED,
  CHARACTER_CREATION_HISTORY_TRAINED,
  CHARACTER_CREATION_OUTLOOK,
  CHARACTER_CREATION_ROLE,
  CHARACTER_CREATION_PRIORITIES_METATYPE,
  CHARACTER_CREATION_PRIORITIES_SPECIAL,
  CHARACTER_CREATION_PRIORITIES_A,
  CHARACTER_CREATION_PRIORITIES_B,
  CHARACTER_CREATION_PRIORITIES_C,
  CHARACTER_CREATION_PRIORITIES_D,
  CHARACTER_CREATION_PRIORITIES_E,
} from "../index"

export const GET_CHARACTER = selector({
  key: 'GET_CHARACTER',
  get: ({get}) => {
    return {
      id: 1,
      history: {
        birth: get(CHARACTER_CREATION_HISTORY_BIRTH),
        raised: get(CHARACTER_CREATION_HISTORY_RAISED),
        trained: get(CHARACTER_CREATION_HISTORY_TRAINED),
        now: get(CHARACTER_CREATION_HISTORY_NOW),
        outlook: get(CHARACTER_CREATION_OUTLOOK)
      },
      name: "Rocinante",
      metatype: get(CHARACTER_CREATION_PRIORITIES_METATYPE),
      role: get(CHARACTER_CREATION_ROLE),
      special: get(CHARACTER_CREATION_PRIORITIES_SPECIAL),
      priorities: {
        A: get(CHARACTER_CREATION_PRIORITIES_A),
        B: get(CHARACTER_CREATION_PRIORITIES_B),
        C: get(CHARACTER_CREATION_PRIORITIES_C),
        D: get(CHARACTER_CREATION_PRIORITIES_D),
        E: get(CHARACTER_CREATION_PRIORITIES_E),
      }
    };
  },
});
